dataset_root: D:\ACADEMICS\THESIS\Datasets\FF\c40\manipulated_sequences # Replace with your actual path
output_dir: D:\ACADEMICS\THESIS\Datasets\FF\c40\preprocessed_frames\tempDeepFakes # Where to save processed frames (relative to project root)
landmark_model_path: D:\ACADEMICS\THESIS\temp\spotting-the-unseen\task1_data_acquisition_preprocessing\ff++ (c40)\scripts\shape_predictor_68_face_landmarks.dat
frame_interval: 10 # Process every 10th frame
yaw_threshold: 30 # Max head rotation in yaw direction
pitch_threshold: 30 # Max head rotation in pitch direction
roll_threshold: 30 # Max head rotation in roll direction
