# Model configuration
model:
  name: "Recce"
  num_classes: 1  # Binary classification (real/fake)

# Training configuration
config:
  lambda_1: 0.1
  lambda_2: 0.1
  optimizer: "adam"
  lr: 0.0002
  weight_decay: 0.00001
  scheduler: "StepLR"
  step_size: 100
  gamma: 0.5

# Experiment configuration
exp:
  exp_id: "test_run"  # Generic experiment ID
  loss: "binary_ce"

# Data configuration
data:
  train_batch_size: 8
  val_batch_size: 8
  test_batch_size: 8
  dataset_file: "./config/dataset/dataset_test.yml"  # Updated dataset config path

# Training settings
train:
  num_epochs: 10
  val_interval: 5
  device: "mps"  # For Apple Silicon
  distributed: false
  backend: "gloo"
  world_size: 1
  rank: 0
  dist_url: "tcp://localhost:23456" 