dataset_root: D:\.THESIS\ff++\manipulated_sequences # Replace with your actual path
output_dir: D:\.THESIS\ff++\preprocessed_frames # Where to save processed frames (relative to project root)
landmark_model_path: C:\Users\aizur\OneDrive\Documents\GitHub\spotting-the-unseen\task1_data_acquisition_preprocessing\ff++ (c23)\scripts\shape_predictor_68_face_landmarks.dat
frame_interval: 10 # Process every 10th frame
yaw_threshold: 30 # Max head rotation in yaw direction
pitch_threshold: 30 # Max head rotation in pitch direction
roll_threshold: 30 # Max head rotation in roll direction
