# Dataset configuration for full training
train_cfg:
  transform:
    image_size: [256, 256]
    num_workers: 4
    pin_memory: true
  balance: true  # Keep this to ensure balanced classes

val_cfg:
  transform:
    image_size: [256, 256]
    num_workers: 4
    pin_memory: true
  balance: true

test_cfg:
  transform:
    image_size: [256, 256]
    num_workers: 4
    pin_memory: true
  balance: true 