dataset_root: datasets\celebdf-v2-unaltered # Replace with your actual path
output_dir: datasets\celebdf-preprocessed-cropped # Where to save processed frames (relative to project root)
landmark_model_path: task1_data_acquisition_preprocessing\celebdf\shape_predictor_68_face_landmarks.dat
frame_interval: 10 # Process every 10th frame
yaw_threshold: 30 # Max head rotation in yaw direction
pitch_threshold: 30 # Max head rotation in pitch direction
roll_threshold: 30 # Max head rotation in roll direction
